# Generated by Django 5.0.7 on 2025-06-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('insId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('insName', models.CharField(max_length=100)),
                ('insIc', models.CharField(max_length=100)),
                ('insEmail', models.EmailField(max_length=254)),
                ('insNumber', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progTitle', models.CharField(max_length=100)),
                ('progDescription', models.TextField()),
                ('progDate', models.DateField()),
                ('progTime', models.TimeField()),
                ('progVenue', models.CharField(max_length=50)),
                ('progCapacity', models.IntegerField()),
                ('progInstructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='religiousprogram.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedName', models.CharField(max_length=100)),
                ('feedMessage', models.TextField()),
                ('feedProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='religiousprogram.program')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regName', models.CharField(max_length=100)),
                ('regIc', models.CharField(max_length=100)),
                ('regEmail', models.EmailField(max_length=254)),
                ('regProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='religiousprogram.program')),
            ],
        ),
    ]
