# Generated by Django 5.0.7 on 2025-06-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religiousprogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='progRegistration',
            field=models.BooleanField(default=False),
        ),
    ]
